//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XJigsaw.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_zh_CN {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_zh_CN() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("XJigsaw.Resources.AppResources.zh-CN", typeof(AppResources_zh_CN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_Zidong {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_Zidong", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_Title {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_Title", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_Warning {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_Warning", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_ConfirmDeleteAllData {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_ConfirmDeleteAllData", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_Yes {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_Yes", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_No {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_No", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_ConfirmDeleteCurrent {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_ConfirmDeleteCurrent", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_PictureSize {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_PictureSize", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_PictureLevel {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_PictureLevel", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_PictureSteps {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_PictureSteps", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_PictureRatio {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_PictureRatio", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_PictureCreationDate {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_PictureCreationDate", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_HistorySelect {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_HistorySelect", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_HistoryDelete {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_HistoryDelete", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_HistoryTotalCount {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_HistoryTotalCount", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_GameMode {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_GameMode", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_SaveJigsawSucceed {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_SaveJigsawSucceed", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_SaveJigsawNotes {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_SaveJigsawNotes", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_OK {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_OK", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_Success {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_Success", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_TimeUsed {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_TimeUsed", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_CongratuateNextLevel {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_CongratuateNextLevel", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_Confirm {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_Confirm", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_Congratulation {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_Congratulation", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_Infor {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_Infor", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_Failed {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_Failed", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_SplitImage {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_SplitImage", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_BuildImage {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_BuildImage", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_ConfirmNewGame {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_ConfirmNewGame", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_ConfirmToInit {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_ConfirmToInit", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_ResetJigsaw {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_ResetJigsaw", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_GamePause {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_GamePause", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_ConfirmQuitGame {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_ConfirmQuitGame", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_ChooseAnImage {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_ChooseAnImage", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_ChooseImage {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_ChooseImage", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_ImageLibrary {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_ImageLibrary", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_Canel {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_Canel", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_Snapshot {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_Snapshot", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_TakePhote {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_TakePhote", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_UserName {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_UserName", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_UserLevel {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_UserLevel", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_SettingPictureLevel {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_SettingPictureLevel", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_SettingPictureRatio {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_SettingPictureRatio", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_SettingPictureTransparent {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_SettingPictureTransparent", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_SettingSound {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_SettingSound", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_DefaultUserName {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_DefaultUserName", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_TabSaveHistory {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_TabSaveHistory", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_TabLocal {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_TabLocal", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_TabServer {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_TabServer", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_TabJigsaw {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_TabJigsaw", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_TabSourceImage {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_TabSourceImage", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_TabSetting {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_TabSetting", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_TabAbout {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_TabAbout", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_AD_Playing {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_AD_Playing", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_AD_Loading {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_AD_Loading", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_AD_UserLeaving {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_AD_UserLeaving", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_AD_FailedLoading {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_AD_FailedLoading", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_AD_StartPlaying {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_AD_StartPlaying", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_AD_StartLoading {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_AD_StartLoading", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_About_Warning {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_About_Warning", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_About_Author {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_About_Author", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_About_Author_Name {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_About_Author_Name", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_About_BestScore {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_About_BestScore", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_About_Version {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_About_Version", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_History_Loacal_Infor {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_History_Loacal_Infor", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_BestScore_NewRecord {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_BestScore_NewRecord", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_About_Note {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_About_Note", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_History_Local_SelectedCount {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_History_Local_SelectedCount", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_History_Local_SelectedNote {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_History_Local_SelectedNote", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_History_Loacal_DB_Size {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_History_Loacal_DB_Size", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_History_Loacal_NoUpdates {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_History_Loacal_NoUpdates", resourceCulture);
            }
        }
        
        internal static string XJigsaw_Jigsaw_About_Build {
            get {
                return ResourceManager.GetString("XJigsaw_Jigsaw_About_Build", resourceCulture);
            }
        }
    }
}
